# Generated by Django 2.2.4 on 2022-05-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_category_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
